export const categories = [
  'Artist',
  'Videography',
  'Food',
  'Designers',
  'Photography',
  'Make-up and Hair',
  'Jewellery',
  'Grocery Store',
  'Event Planner',
  'DJ',
  'Decor and Flowers',
  'Clothes and Fashion',
  'Banquet Halls',
  'Bakers',
];

export const categories_photos = [
  '/images/Artist.jpeg',
  '/images/Videography.jpeg',
  '/images/Food.jpeg',
  '/images/Designer.jpeg',
  '/images/Photography.jpeg',
  '/images/Makeup_Hair.jpeg',
  '/images/Jewellery.jpeg',
  '/images/Groceries.jpeg',
  '/images/Event_Planning.jpeg',
  '/images/DJ.jpeg',
  '/images/Decor.jpeg',
  '/images/Fashion.jpeg',
  '/images/Banquet_Hall.jpeg',
  '/images/Bakers.jpeg',
];
